random-xs:
  pyanns:
    docker-tag: neurips23-ood-fuse
    module: neurips23.ood.fuse.fuse
    constructor: Fuse
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R":32, "L":50}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
  pyanns:
    docker-tag: neurips23-ood-fuse
    module: neurips23.ood.fuse.fuse
    constructor: Fuse
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R":48, "L":500, "buildthreads" : 16}]
        query-args: |
          [
          {"ef":90},
          {"ef":95},
          {"ef":100},
          {"ef":110},
          {"ef":115},
          {"ef":125},
          {"ef":130},
          {"ef":135},
          {"ef":140},
          {"ef":145}
          ]